let mediaContent = [{id: 1, topic: 'JavaScript - Introduction', subTopic: 'Significance and Origin of JavaScript', media: 'https://player.vimeo.com/video/519893527'},
{id: 2, topic: 'JavaScript - Introduction', subTopic: 'Visual Studio Code Installation', media: 'https://player.vimeo.com/video/519894365'},
{id: 3, topic: 'JavaScript - Introduction', subTopic: 'Live Server Plugin Installation', media: 'https://player.vimeo.com/video/519894397'},
{id: 4, topic: 'JavaScript - Hello World', subTopic: 'Display Hello World in console', media: 'https://player.vimeo.com/video/519896189'},
{id: 5, topic: 'JavaScript - Hello World', subTopic: 'Create Folder', media: 'https://player.vimeo.com/video/519896939'},
{id: 6, topic: 'JavaScript - Hello World', subTopic: 'Open javascript folder in Visual Studio Code', media: 'https://player.vimeo.com/video/519896987'},
{id: 7, topic: 'JavaScript - Hello World', subTopic: 'Create HTML file', media: 'https://player.vimeo.com/video/519897051'},
{id: 8, topic: 'JavaScript - Hello World', subTopic: 'Key in the code', media: 'https://player.vimeo.com/video/519897088'},
{id: 9, topic: 'JavaScript - Hello World', subTopic: 'Launch HTML using Live Server', media: 'https://player.vimeo.com/video/519897141'},
{id: 10, topic: 'JavaScript - Hello World', subTopic: 'Place Visual Studio Code and Chrome browser adjacently', media: 'https://player.vimeo.com/video/519897210'},
{id: 11, topic: 'JavaScript - Hello World', subTopic: 'Placement of Script tag', media: 'https://player.vimeo.com/video/519897257'},
{id: 12, topic: 'JavaScript - Hello World', subTopic: 'JavaScript is Case Sensitive', media: 'https://player.vimeo.com/video/519897331'},
{id: 13, topic: 'JavaScript - Hello World', subTopic: 'Code Execution Flow', media: 'https://player.vimeo.com/video/519897372'},
{id: 14, topic: 'JavaScript - Literals and Arithmetic Operators', subTopic: 'Temperature Conversion Calculation', media: 'https://player.vimeo.com/video/519902093'},
{id: 15, topic: 'JavaScript - Literals and Arithmetic Operators', subTopic: 'Create HTML file', media: 'https://player.vimeo.com/video/519902131'},
{id: 16, topic: 'JavaScript - Literals and Arithmetic Operators', subTopic: 'Copy HTML code from hello.html', media: 'https://player.vimeo.com/video/519902171'},
{id: 17, topic: 'JavaScript - Literals and Arithmetic Operators', subTopic: 'Difference between a String Literal and Numeric Literal', media: 'https://player.vimeo.com/video/519902228'},
{id: 18, topic: 'JavaScript - Literals and Arithmetic Operators', subTopic: 'Understanding Arithmetic Addition and String Concatenation', media: 'https://player.vimeo.com/video/519902291'},
{id: 19, topic: 'JavaScript - Literals and Arithmetic Operators', subTopic: 'Code to display Celsius', media: 'https://player.vimeo.com/video/519902360'},
{id: 20, topic: 'JavaScript - Literals and Arithmetic Operators', subTopic: 'Calculation code for Fahrenheit', media: 'https://player.vimeo.com/video/519902402'},
{id: 21, topic: 'JavaScript - Literals and Arithmetic Operators', subTopic: 'Understanding Operator Precedence', media: 'https://player.vimeo.com/video/519902450'},
{id: 22, topic: 'JavaScript - Literals and Arithmetic Operators', subTopic: 'Fix Fahrenheit calculation issue', media: 'https://player.vimeo.com/video/519902516'},
{id: 23, topic: 'JavaScript - Literals and Arithmetic Operators', subTopic: 'Summary', media: 'https://player.vimeo.com/video/519902572'},
{id: 24, topic: 'JavaScript - Variables', subTopic: 'Limitations of Fahrenheit conversion code', media: 'https://player.vimeo.com/video/519904848'},
{id: 25, topic: 'JavaScript - Variables', subTopic: 'Implementing Variables', media: 'https://player.vimeo.com/video/519904906'},
{id: 26, topic: 'JavaScript - Variables', subTopic: 'Defining multiple variables', media: 'https://player.vimeo.com/video/519904966'},
{id: 27, topic: 'JavaScript - Variables', subTopic: 'String variable and Variable Naming Convention', media: 'https://player.vimeo.com/video/519905012'},
{id: 28, topic: 'JavaScript - Variables', subTopic: 'Multiple variable definitions in a single line', media: 'https://player.vimeo.com/video/519905083'},
{id: 29, topic: 'JavaScript - Function', subTopic: 'Significance of Function', media: 'https://player.vimeo.com/video/519913528'},
{id: 30, topic: 'JavaScript - Function', subTopic: 'Define Function', media: 'https://player.vimeo.com/video/519913572'},
{id: 31, topic: 'JavaScript - Function', subTopic: 'Call Function', media: 'https://player.vimeo.com/video/519913622'},
{id: 32, topic: 'JavaScript - Function', subTopic: 'Function with Parameter', media: 'https://player.vimeo.com/video/519913674'},
{id: 33, topic: 'JavaScript - Function', subTopic: 'Call Function from another Web Page', media: 'https://player.vimeo.com/video/519913720'},
{id: 34, topic: 'JavaScript - Function', subTopic: 'Steps to implement External Script', media: 'https://player.vimeo.com/video/519913751'},
{id: 35, topic: 'JavaScript - Function', subTopic: 'Function definition in Script File', media: 'https://player.vimeo.com/video/519913804'},
{id: 36, topic: 'JavaScript - Function', subTopic: 'Move Function to Script file', media: 'https://player.vimeo.com/video/519913860'},
{id: 37, topic: 'JavaScript - Function', subTopic: 'Refer Script File from HTML', media: 'https://player.vimeo.com/video/519913933'},
{id: 38, topic: 'JavaScript - Function', subTopic: 'Additional information about External JavaScript File', media: 'https://player.vimeo.com/video/519913984'},
{id: 39, topic: 'JavaScript - Function', subTopic: 'Return Statement in a Function', media: 'https://player.vimeo.com/video/519914036'},
{id: 40, topic: 'JavaScript - Function', subTopic: 'Code Execution Flow of a Function', media: 'https://player.vimeo.com/video/519914113'},
{id: 41, topic: 'JavaScript - Function', subTopic: 'About Functions and Function Naming Conventions', media: 'https://player.vimeo.com/video/519914162'},
{id: 42, topic: 'JavaScript - Conditional Statements', subTopic: 'About Conditional Statements', media: 'https://player.vimeo.com/video/519919000'},
{id: 43, topic: 'JavaScript - Conditional Statements', subTopic: 'Problem Statement to learn Conditional Statements', media: 'https://player.vimeo.com/video/519919045'},
{id: 44, topic: 'JavaScript - Conditional Statements', subTopic: 'Implement if statement', media: 'https://player.vimeo.com/video/519919101'},
{id: 45, topic: 'JavaScript - Conditional Statements', subTopic: 'Explain if statement', media: 'https://player.vimeo.com/video/519919149'},
{id: 46, topic: 'JavaScript - Conditional Statements', subTopic: 'Implement if statement for raining check', media: 'https://player.vimeo.com/video/519919204'},
{id: 47, topic: 'JavaScript - Conditional Statements', subTopic: 'Implement Logical NOT operator', media: 'https://player.vimeo.com/video/519919261'},
{id: 48, topic: 'JavaScript - Conditional Statements', subTopic: 'Explanation for Logical NOT operator', media: 'https://player.vimeo.com/video/519919552'},
{id: 49, topic: 'JavaScript - Conditional Statements', subTopic: 'Implement else block', media: 'https://player.vimeo.com/video/519919602'},
{id: 50, topic: 'JavaScript - Conditional Statements', subTopic: 'Implement Equal (==) operator', media: 'https://player.vimeo.com/video/519919670'},
{id: 51, topic: 'JavaScript - Conditional Statements', subTopic: 'Implement Strict Equal (===) operator', media: 'https://player.vimeo.com/video/519919734'},
{id: 52, topic: 'JavaScript - Conditional Statements', subTopic: 'Comparison Operators', media: 'https://player.vimeo.com/video/519919782'},
{id: 53, topic: 'JavaScript - Conditional Statements', subTopic: 'Logical Operators', media: 'https://player.vimeo.com/video/519919849'},
{id: 54, topic: 'JavaScript - Conditional Statements', subTopic: 'About Pipe Character', media: 'https://player.vimeo.com/video/519919894'},
{id: 55, topic: 'JavaScript - Conditional Statements', subTopic: 'Problem Statement - Airlines Infant Policy', media: 'https://player.vimeo.com/video/519919956'},
{id: 56, topic: 'JavaScript - Conditional Statements', subTopic: 'Implement infant age check', media: 'https://player.vimeo.com/video/519920008'},
{id: 57, topic: 'JavaScript - Conditional Statements', subTopic: 'Implement adult age check', media: 'https://player.vimeo.com/video/519920090'},
{id: 58, topic: 'JavaScript - Conditional Statements', subTopic: 'Children classification explained', media: 'https://player.vimeo.com/video/519920158'},
{id: 59, topic: 'JavaScript - Conditional Statements', subTopic: 'Implement children check', media: 'https://player.vimeo.com/video/519920221'},
{id: 60, topic: 'JavaScript - Conditional Statements', subTopic: 'Solve Infant Policy using else if', media: 'https://player.vimeo.com/video/519920291'},
{id: 61, topic: 'JavaScript - Conditional Statements', subTopic: 'Benefits of else if', media: 'https://player.vimeo.com/video/519920355'},
{id: 62, topic: 'JavaScript - Conditional Statements', subTopic: 'Implement Ternary Operator', media: 'https://player.vimeo.com/video/519920430'},
{id: 63, topic: 'JavaScript - Conditional Statements', subTopic: 'Explain Ternary Operator', media: 'https://player.vimeo.com/video/519920513'},
{id: 64, topic: 'JavaScript - Conditional Statements', subTopic: 'Understand Swich Case', media: 'https://player.vimeo.com/video/519920582'},
{id: 65, topic: 'JavaScript - Conditional Statements', subTopic: 'Summary for Conditional Statements', media: 'https://player.vimeo.com/video/519920650'},
{id: 66, topic: 'JavaScript - Looping Constructs', subTopic: 'Important of Looping Constructs', media: 'https://player.vimeo.com/video/519919551'},
{id: 67, topic: 'JavaScript - Looping Constructs', subTopic: 'Display numbers from 1 to 5', media: 'https://player.vimeo.com/video/519919613'},
{id: 68, topic: 'JavaScript - Looping Constructs', subTopic: 'Display numbers from 1 to 5 using while', media: 'https://player.vimeo.com/video/519919665'},
{id: 69, topic: 'JavaScript - Looping Constructs', subTopic: 'How while works?', media: 'https://player.vimeo.com/video/519919722'},
{id: 70, topic: 'JavaScript - Looping Constructs', subTopic: 'Display numbers from 1 to 5 using do .. while', media: 'https://player.vimeo.com/video/519919773'},
{id: 71, topic: 'JavaScript - Looping Constructs', subTopic: 'Display numbers from 1 to 5 using for', media: 'https://player.vimeo.com/video/519919843'},
{id: 72, topic: 'JavaScript - Looping Constructs', subTopic: 'TV Schedule - Problem Statement', media: 'https://player.vimeo.com/video/519919889'},
{id: 73, topic: 'JavaScript - Looping Constructs', subTopic: 'TV Schedule Problem - Partial Solution', media: 'https://player.vimeo.com/video/519919939'},
{id: 74, topic: 'JavaScript - Looping Constructs', subTopic: 'TV Schedule Problem - Solved', media: 'https://player.vimeo.com/video/519919999'},
{id: 75, topic: 'JavaScript - Looping Constructs', subTopic: 'Increment and Decrement operators', media: 'https://player.vimeo.com/video/519920060'},
{id: 76, topic: 'JavaScript - Looping Constructs', subTopic: 'Assignment Operators', media: 'https://player.vimeo.com/video/519920118'},
{id: 77, topic: 'JavaScript - Arrays', subTopic: 'Importance of Arrays', media: 'https://player.vimeo.com/video/519939807'},
{id: 78, topic: 'JavaScript - Arrays', subTopic: 'Defining an Array', media: 'https://player.vimeo.com/video/519939854'},
{id: 79, topic: 'JavaScript - Arrays', subTopic: 'Read array items using index', media: 'https://player.vimeo.com/video/519939925'},
{id: 80, topic: 'JavaScript - Arrays', subTopic: 'Modify and Add item in an array', media: 'https://player.vimeo.com/video/519939976'},
{id: 81, topic: 'JavaScript - Arrays', subTopic: 'Calculate Average', media: 'https://player.vimeo.com/video/519940100'},
{id: 82, topic: 'JavaScript - Arrays', subTopic: 'Calculate Average using for - Display array items', media: 'https://player.vimeo.com/video/519940162'},
{id: 83, topic: 'JavaScript - Arrays', subTopic: 'Calculate Average using for - Calculate average', media: 'https://player.vimeo.com/video/519940242'},
{id: 84, topic: 'JavaScript - Arrays', subTopic: 'Array length property', media: 'https://player.vimeo.com/video/519940316'},
{id: 85, topic: 'JavaScript - Object', subTopic: 'Passenger details as object', media: 'https://player.vimeo.com/video/519940252'},
{id: 86, topic: 'JavaScript - Object', subTopic: 'Limitations of variables and arrays', media: 'https://player.vimeo.com/video/519940303'},
{id: 87, topic: 'JavaScript - Object', subTopic: 'Implementing object for one passenger', media: 'https://player.vimeo.com/video/519940398'},
{id: 88, topic: 'JavaScript - Object', subTopic: 'Additional passenger details', media: 'https://player.vimeo.com/video/519940436'},
{id: 89, topic: 'JavaScript - Object', subTopic: 'Implementing additional passenger details', media: 'https://player.vimeo.com/video/519940522'},
{id: 90, topic: 'JavaScript - Object', subTopic: 'Implementing gender object', media: 'https://player.vimeo.com/video/519940585'},
{id: 91, topic: 'JavaScript - Object', subTopic: 'Implementing single passenger in an array', media: 'https://player.vimeo.com/video/519940636'},
{id: 92, topic: 'JavaScript - Object', subTopic: 'Implementing all passengers in the array', media: 'https://player.vimeo.com/video/519940682'},
{id: 93, topic: 'JavaScript - Object', subTopic: 'Summary', media: 'https://player.vimeo.com/video/519940739'},
{id: 94, topic: 'JavaScript - Class', subTopic: 'Problem Statement', media: 'https://player.vimeo.com/video/519941009'},
{id: 95, topic: 'JavaScript - Class', subTopic: 'Implement full name display for one passenger', media: 'https://player.vimeo.com/video/519941056'},
{id: 96, topic: 'JavaScript - Class', subTopic: 'Implement full name display using function', media: 'https://player.vimeo.com/video/519941110'},
{id: 97, topic: 'JavaScript - Class', subTopic: 'Implement full name function within the object', media: 'https://player.vimeo.com/video/519941199'},
{id: 98, topic: 'JavaScript - Class', subTopic: 'Limitations of objects', media: 'https://player.vimeo.com/video/519941277'},
{id: 99, topic: 'JavaScript - Class', subTopic: 'Implement Class definition', media: 'https://player.vimeo.com/video/519941330'},
{id: 100, topic: 'JavaScript - Class', subTopic: 'Implement Constructor definition', media: 'https://player.vimeo.com/video/519941379'},
{id: 101, topic: 'JavaScript - Class', subTopic: 'Implement Object creation based on Class', media: 'https://player.vimeo.com/video/519941474'},
{id: 102, topic: 'JavaScript - Class', subTopic: 'Explain code execution flow', media: 'https://player.vimeo.com/video/519941548'},
{id: 103, topic: 'JavaScript - Class', subTopic: 'Difference between a Class and Object', media: 'https://player.vimeo.com/video/519941632'},
{id: 104, topic: 'JavaScript - Class', subTopic: 'Implement Gender Object creation', media: 'https://player.vimeo.com/video/519941696'},
{id: 105, topic: 'JavaScript - Class', subTopic: 'Implement Passenger Class definition', media: 'https://player.vimeo.com/video/519941780'},
{id: 106, topic: 'JavaScript - Class', subTopic: 'Implement method in Passenger class to get full name', media: 'https://player.vimeo.com/video/519941835'},
{id: 107, topic: 'JavaScript - Class', subTopic: 'Implement multiple Passenger object creation using Class', media: 'https://player.vimeo.com/video/519941917'},
{id: 108, topic: 'JavaScript - Class', subTopic: 'Benefits of using Class', media: 'https://player.vimeo.com/video/519941972'},
{id: 109, topic: 'JavaScript - Module', subTopic: 'Introduction to Modules', media: 'https://player.vimeo.com/video/519941576'},
{id: 110, topic: 'JavaScript - Module', subTopic: 'Implement Class definition in external script file', media: 'https://player.vimeo.com/video/519941621'},
{id: 111, topic: 'JavaScript - Module', subTopic: 'Airlines application complexity', media: 'https://player.vimeo.com/video/519941680'},
{id: 112, topic: 'JavaScript - Module', subTopic: 'Limitations of using script tag', media: 'https://player.vimeo.com/video/519941739'},
{id: 113, topic: 'JavaScript - Module', subTopic: 'Implement using Modules', media: 'https://player.vimeo.com/video/519941808'},
{id: 114, topic: 'JavaScript - Variable Scoping', subTopic: 'Introduction to Variable Scoping', media: 'https://player.vimeo.com/video/519942101'},
{id: 115, topic: 'JavaScript - Variable Scoping', subTopic: 'Demonstration of Global and Functional variables', media: 'https://player.vimeo.com/video/519942164'},
{id: 116, topic: 'JavaScript - Variable Scoping', subTopic: 'Demonstration of Block Scope using let and const', media: 'https://player.vimeo.com/video/519942242'},
{id: 117, topic: 'JavaScript - Variable Scoping', subTopic: 'Which one to use? let or var', media: 'https://player.vimeo.com/video/519942314'},
{id: 118, topic: 'JavaScript - Arrow Functions', subTopic: 'Introduction to Arrow Functions', media: 'https://player.vimeo.com/video/519942367'},
{id: 119, topic: 'JavaScript - Arrow Functions', subTopic: 'Assign function to a variable', media: 'https://player.vimeo.com/video/519942421'},
{id: 120, topic: 'JavaScript - Arrow Functions', subTopic: 'Implement Arrow Function with brackets', media: 'https://player.vimeo.com/video/519942484'},
{id: 121, topic: 'JavaScript - Arrow Functions', subTopic: 'Implement Arrow Function without brackets', media: 'https://player.vimeo.com/video/519942543'},
{id: 122, topic: 'JavaScript - Arrow Functions', subTopic: 'Implement Arrow Function with parameters', media: 'https://player.vimeo.com/video/519942593'},
{id: 123, topic: 'JavaScript - Arrow Functions', subTopic: 'Benefits of Arrow Function', media: 'https://player.vimeo.com/video/519942659'},
{id: 124, topic: 'JavaScript - Arrow Functions', subTopic: 'Understanding reduce function of array', media: 'https://player.vimeo.com/video/519942709'},
{id: 125, topic: 'JavaScript - Arrow Functions', subTopic: 'Implement total calculation using function', media: 'https://player.vimeo.com/video/519942805'},
{id: 126, topic: 'JavaScript - Arrow Functions', subTopic: 'Implement total calculation using Arrow Function', media: 'https://player.vimeo.com/video/519942859'},
{id: 127, topic: 'JavaScript - DOM', subTopic: 'What is a Document in DOM?', media: 'https://player.vimeo.com/video/519942756'},
{id: 128, topic: 'JavaScript - DOM', subTopic: 'What is an Object Model in DOM?', media: 'https://player.vimeo.com/video/519942826'},
{id: 129, topic: 'JavaScript - DOM', subTopic: 'What is DOM?', media: 'https://player.vimeo.com/video/519942887'},
{id: 130, topic: 'JavaScript - DOM', subTopic: 'Window Object', media: 'https://player.vimeo.com/video/519942937'},
{id: 131, topic: 'JavaScript - DOM', subTopic: 'Implement closure of browser tab', media: 'https://player.vimeo.com/video/519943011'},
{id: 132, topic: 'JavaScript - DOM', subTopic: 'Defining window object is optional', media: 'https://player.vimeo.com/video/519943066'},
{id: 133, topic: 'JavaScript - DOM', subTopic: 'Implement getElementById()', media: 'https://player.vimeo.com/video/519943125'},
{id: 134, topic: 'JavaScript - DOM', subTopic: 'Implement innerText property', media: 'https://player.vimeo.com/video/519943175'},
{id: 135, topic: 'JavaScript - DOM', subTopic: 'Implement innerHTML property', media: 'https://player.vimeo.com/video/519943302'},
{id: 136, topic: 'JavaScript - DOM', subTopic: 'Implement attribute manipulation', media: 'https://player.vimeo.com/video/519943370'},
{id: 137, topic: 'JavaScript - DOM', subTopic: 'Implement value property', media: 'https://player.vimeo.com/video/519943589'},
{id: 138, topic: 'JavaScript - DOM', subTopic: 'Implement style property', media: 'https://player.vimeo.com/video/519943476'},
{id: 139, topic: 'JavaScript - DOM', subTopic: 'Implement classname property', media: 'https://player.vimeo.com/video/519943555'},
{id: 140, topic: 'JavaScript - DOM', subTopic: 'Implement getElementsByClassName()', media: 'https://player.vimeo.com/video/519943612'},
{id: 141, topic: 'JavaScript - DOM', subTopic: 'Other methods in document to get element', media: 'https://player.vimeo.com/video/519943677'},
{id: 142, topic: 'JavaScript - DOM', subTopic: 'Introduction to DOM Events', media: 'https://player.vimeo.com/video/519943749'},
{id: 143, topic: 'JavaScript - DOM', subTopic: 'Implement Mouse Click Event', media: 'https://player.vimeo.com/video/519943826'},
{id: 144, topic: 'JavaScript - DOM', subTopic: 'Implement linking of an event with a function', media: 'https://player.vimeo.com/video/519957631'},
{id: 145, topic: 'JavaScript - DOM', subTopic: 'Implementing Event Listener', media: 'https://player.vimeo.com/video/519958624'},
{id: 146, topic: 'JavaScript - DOM', subTopic: 'Implement keyup event', media: 'https://player.vimeo.com/video/519958956'},
{id: 147, topic: 'JavaScript - Apply DOM - Infant Policy', subTopic: 'Display Passenger Category using Form', media: 'https://player.vimeo.com/video/519943247'},
{id: 148, topic: 'JavaScript - Apply DOM - Infant Policy', subTopic: 'Implement HTML', media: 'https://player.vimeo.com/video/519943305'},
{id: 149, topic: 'JavaScript - Apply DOM - Infant Policy', subTopic: 'Implement getting HTML elements', media: 'https://player.vimeo.com/video/519943363'},
{id: 150, topic: 'JavaScript - Apply DOM - Infant Policy', subTopic: 'Implement click event', media: 'https://player.vimeo.com/video/519943405'},
{id: 151, topic: 'JavaScript - Apply DOM - Infant Policy', subTopic: 'Implement inclusion of category computation logic', media: 'https://player.vimeo.com/video/519943451'},
{id: 152, topic: 'JavaScript - Apply DOM - Infant Policy', subTopic: 'Implement display of category based on age', media: 'https://player.vimeo.com/video/519943522'},
{id: 153, topic: 'JavaScript - Apply DOM - Infant Policy', subTopic: 'Displaying Passenger Category as we type', media: 'https://player.vimeo.com/video/519943583'},
{id: 154, topic: 'JavaScript - Apply DOM - Infant Policy', subTopic: 'Implement display of category when typing age', media: 'https://player.vimeo.com/video/519943642'},
{id: 155, topic: 'JavaScript - Apply DOM - Infant Policy', subTopic: 'Defect in the implementation', media: 'https://player.vimeo.com/video/519943714'},
{id: 156, topic: 'JavaScript - Apply DOM - Infant Policy', subTopic: 'Fix Defect', media: 'https://player.vimeo.com/video/519943766'},
{id: 157, topic: 'JavaScript - Apply DOM - Infant Policy', subTopic: 'Explain importance of validation', media: 'https://player.vimeo.com/video/519943841'},
{id: 158, topic: 'JavaScript - Apply DOM - Infant Policy', subTopic: 'Include div for displaying validation message', media: 'https://player.vimeo.com/video/519943904'},
{id: 159, topic: 'JavaScript - Apply DOM - Infant Policy', subTopic: 'Get the validation message div element', media: 'https://player.vimeo.com/video/519943936'},
{id: 160, topic: 'JavaScript - Apply DOM - Infant Policy', subTopic: 'Hide the validation message', media: 'https://player.vimeo.com/video/519943993'},
{id: 161, topic: 'JavaScript - Apply DOM - Infant Policy', subTopic: 'Implement validation', media: 'https://player.vimeo.com/video/519944046'},
{id: 162, topic: 'JavaScript - Apply DOM - Search Student', subTopic: 'How search student interface should work?', media: 'https://player.vimeo.com/video/519944276'},
{id: 163, topic: 'JavaScript - Apply DOM - Search Student', subTopic: 'Explain HTML content', media: 'https://player.vimeo.com/video/519944326'},
{id: 164, topic: 'JavaScript - Apply DOM - Search Student', subTopic: 'Implement hiding of names when page is displayed', media: 'https://player.vimeo.com/video/519944374'},
{id: 165, topic: 'JavaScript - Apply DOM - Search Student', subTopic: 'Implement getting HTML elements', media: 'https://player.vimeo.com/video/519944407'},
{id: 166, topic: 'JavaScript - Apply DOM - Search Student', subTopic: 'Implement addition of event listener', media: 'https://player.vimeo.com/video/519944453'},
{id: 167, topic: 'JavaScript - Apply DOM - Search Student', subTopic: 'Explain logic to display matching names', media: 'https://player.vimeo.com/video/519944500'},
{id: 168, topic: 'JavaScript - Apply DOM - Search Student', subTopic: 'Implement getting all names from div', media: 'https://player.vimeo.com/video/519944556'},
{id: 169, topic: 'JavaScript - Apply DOM - Search Student', subTopic: 'Implement filtering', media: 'https://player.vimeo.com/video/519944639'},
{id: 170, topic: 'JavaScript - Apply DOM - Search Student', subTopic: 'Implement fixing of defect', media: 'https://player.vimeo.com/video/519944694'},
{id: 171, topic: 'JavaScript - Apply DOM - Search Student', subTopic: 'Implement event for name selection', media: 'https://player.vimeo.com/video/519944787'},
{id: 172, topic: 'JavaScript - Apply DOM - Search Student', subTopic: 'Implement displaying of name after selection', media: 'https://player.vimeo.com/video/519944842'},
{id: 173, topic: 'JavaScript - DOM Exercise and Conclusion', subTopic: 'Demonstration of application navigation using DOM', media: 'https://player.vimeo.com/video/519944520'},
{id: 174, topic: 'JavaScript - DOM Exercise and Conclusion', subTopic: 'Demonstration of DOM applications available in internet', media: 'https://player.vimeo.com/video/519944582'},
]